'use strict'; const e = require('../../../common/vendor.js'); const i = require('../../../api/config/address.js'); const n = require('../../../store/login/index.js'); const t = require('../../../utils/common/city.js'); const o = require('../../../router/index.js'); if (require('../../../utils/request/index.js'), require('../../../utils/request/constants.js'), require('../../../store/setup.js'), require('../../../store/user/index.js'), require('../../../store/loading/index.js'), require('../../../utils/login/index.js'), require('../../../utils/common/storage.js'), require('../../../api/config/login.js'), require('../../../api/config/integral.js'), !Array)
  (e.resolveComponent('shu-nav-bar') + e.resolveComponent('shu-loading'))()

Math || ((() => '../../../components/common/nav-bar/index.js') + r + (() => '../../../components/common/loading/index.js'))(); const r = () => '../components/uni-data-picker/uni-data-picker.js'; const a = {
  __name: 'index',
  setup(r) {
    const { info: a } = n.useLoginStore(); e.ref(null); const l = e.reactive({ tree: [], modelValue: [], showPicker: !1, localdata: [], title: '添加地址', name: '', tel: '', address: '', detail_info: '', number: '', index: '', city: '', country: '', province: '', zip_code: '', type: '', id: '', shop_id: '' }); e.reactive({ name: '' }), e.onLoad((async (e) => { if (e == null ? void 0 : e.info) { const i = JSON.parse(e.info); l.name = i.name, l.tel = i.tel, l.detail_info = i.detail_info, l.province = i.province, l.city = i.city, l.country = i.country, l.zip_code = i.zip_code, l.id = i.id, l.modelValue = [{ text: i == null ? void 0 : i.province, value: i == null ? void 0 : i.province }, { text: i == null ? void 0 : i.city, value: i == null ? void 0 : i.city }, { text: i == null ? void 0 : i.country, value: i == null ? void 0 : i.country }] }(e == null ? void 0 : e.type) && (l.type = e.type), (e == null ? void 0 : e.shop_id) && (l.shop_id = e.shop_id), l.title = l.type === 'edit' ? '编辑地址' : '添加地址', l.localdata = await (function (e) { const i = []; function n(e, i) { for (const t in e) { const o = []; let r = []; const a = { text: Array.isArray(e) ? e[t] : t, value: Array.isArray(e) ? e[t] : t, children: o }; r = e[t], i.push(a), ['[object Object]', '[object Array]'].includes(Object.prototype.toString.call(r)) && n(r, o) } } return n(e, i), i || [] }(t.provinces)) })); const c = e.computed((() => l.province + l.city + l.country)); function s(e) { let i; if ((i = e == null ? void 0 : e.detail) == null ? void 0 : i.value) { const i = e.detail.value; l.province = i[0].value, l.city = i[1].value, l.country = i[2].value } } function u() { const e = e => e.replaceAll(' ', '').length === 0; return new Promise(((i, n) => { e(l.name) && i('联系人不可以为空'), e(l.tel) && i('手机号不可以为空'), e(l.province + l.city + l.country) && i('地区信息不可以为空'), e(l.detail_info) && i('详细信息不可以为空'), i() })) } function d() {
      l.type == 'setup' && u().then(((n) => { n ? e.index.showToast({ icon: 'none', title: n }) : (async function () { await i.addAddressInfo({ detail_info: l.detail_info, name: l.name, tel: l.tel, user_id: a.user_id, province: l.province, city: l.city, country: l.country }), e.index.showToast({ icon: 'none', title: '添加成功' }), setTimeout(() => { o.router.back() }, 700) }()) })), l.type == 'edit' && u().then(((n) => {
        if (n) { e.index.showToast({ icon: 'none', title: n }) }
        else { const n = { id: l.id, user_id: a.user_id, name: l.name, tel: l.tel, province: l.province, city: l.city, country: l.country, detail_info: l.detail_info, address: 'wosjo' }; i.updataAdress(l.id, n).then(((i) => { e.index.$emit('select_adress', JSON.stringify({ select_adress: n, id: l.id })), e.index.showToast({ icon: 'none', title: '修改成功' }), setTimeout(() => { o.router.back() }, 700) })) }
      }))
    } return l.address = c, (i, n) => ({ a: e.p({ title: e.unref(l).title }), b: e.unref(l).name, c: e.o((i => e.unref(l).name = i.detail.value)), d: e.unref(l).tel, e: e.o((i => e.unref(l).tel = i.detail.value)), f: e.o(s), g: e.o(i.onnodeclick), h: e.p({ 'localdata': e.unref(l).localdata, 'placeholder': e.unref(c) ? '' : '请选择', 'popup-title': '省、市、区', 'model-value': e.unref(l).modelValue }), i: e.t(e.unref(c)), j: e.unref(l).detail_info, k: e.o((i => e.unref(l).detail_info = i.detail.value)), l: e.unref(l).zip_code, m: e.o((i => e.unref(l).zip_code = i.detail.value)), n: e.o(d) })
  },
}; const l = e._export_sfc(a, [['__scopeId', 'data-v-ae3adab2']]); wx.createPage(l)
