'use strict'; const e = require('../../../common/vendor.js'); const o = require('../../../common/assets.js'); const n = require('../../../store/login/index.js'); const r = require('../../../api/config/user.js'); const i = require('../../../api/config/login.js'); const u = require('../../../store/user/index.js'); const t = require('../../../utils/common/upload.js'); const s = require('../../../hooks/usePublicPath/index.js'); if (require('../../../utils/request/index.js'), require('../../../utils/request/constants.js'), require('../../../store/setup.js'), require('../../../store/loading/index.js'), require('../../../utils/login/index.js'), require('../../../utils/common/storage.js'), require('../../../api/config/integral.js'), require('../../../api/config/upload.js'), !Array)
  (e.resolveComponent('shu-nav-bar') + e.resolveComponent('u-icon') + e.resolveComponent('shu-loading'))()

Math || ((() => '../../../components/common/nav-bar/index.js') + (() => '../../../node-modules/uview-plus/components/u-icon/u-icon.js') + a + d + (() => '../../../components/common/loading/index.js'))(); const a = () => '../components/user-sex/index.js'; const d = () => '../components/qushe-picker/qushe-picker.js'; const f = {
  __name: 'index',
  setup(a) {
    const { members: d } = u.useUserStore(); const { info: f } = n.useLoginStore(); const c = e.ref(null); const { $publicPath: l } = s.getPublicPath(); const m = e.ref(null); const I = e.reactive({ userInfo: { icon_uri: '', nickname: '微信昵称', gender: '', birthday: '', mobile: '', tiktok_id: '', weibo_id: '', redbook_id: '' }, focus_info: {}, camera: !1, title: '个人资料', show: !1, date: '' }); async function h() { const e = await i.userCurrent(); I.userInfo = e.user_info } function _(o) { let n; const i = (n = o == null ? void 0 : o.detail) == null ? void 0 : n.avatarUrl; t.uploadImg(i).then(((e) => { let o; (o = { msg: l + e.url }, new Promise(((e, n) => { r.checkImg({ msg: o, openId: f.open_id }).then(((n) => { !0 === n && e(o) })) }))).then((() => { I.userInfo.icon_uri = e == null ? void 0 : e.url, g() })) })).catch((() => { e.index.showToast({ title: '个人中心.头像上传失败', icon: 'none', duration: 2500 }) })) } function k(o) { I.camera || e.index.authorize({ scope: 'scope.camera', success() { I.camera = !0, _(o) } }), I.camera && _(o) } function b(e, o) { I.focus_info[o] = e } async function p(o, n) {
      if (['nickname', 'tiktok_id', 'weibo_id', 'redbook_id'].includes(n) && I.focus_info[n] === o)
        return; if (n && ['tiktok_id', 'weibo_id', 'redbook_id'].includes(n)) {
        const n = await (function (e) { return new Promise(((o, n) => { o(/[\u4E00-\u9FA5a-zA-Z0-9\p{P}]/gu.test(e)) })) }(o)); if (!n)
          return void e.index.showToast({ icon: 'none', title: '未输入内容，请重新输入' })
      }r.textDetection({ msg: o }).then(((o) => { !0 === o ? g() : (I.userInfo[n] = '', e.index.showToast({ icon: 'none', title: '内容不合法，请重新输入' })) }))
    } function g() { r.keepUserInfo({ nickname: I.userInfo.nickname, iconUrl: I.userInfo.icon_uri, gender: I.userInfo.gender, birthday: I.userInfo.birthday, redbookId: I.userInfo.redbook_id, weiboId: I.userInfo.weibo_id, tiktokId: I.userInfo.tiktok_id }).then(((o) => { o == 1 && (d.current.name = I.userInfo.nickname, d.current.gender = I.userInfo.gender, d.current.icon = I.userInfo.icon_uri, d.current.birthday = I.userInfo.birthday, h(), setTimeout(() => { e.index.showToast({ icon: 'none', title: '保存成功' }) }, 700)) })) } function w(e) { I.focus_info.gender !== e && (I.userInfo.gender = e, g()) }e.onShow((() => { h(), e.index.getSetting({ success(e) { I.camera = !!e.authSetting['scope.camera'] } }) })); const v = e.computed((() => I.userInfo.birthday)); function j(e, o) {
      const n = (function (e) { console.log(e.data, 'datadata'); let o = e.data.split('-'); return o = o.map((e => Number(e) < 10 ? `0${e}` : e)), o.join('-') }(e)); if (I.date = n, I.userInfo.birthday === n)
        return !1; I.show = !0
    } function x() { I.userInfo.birthday = I.date, I.show = !1, m.value.hide(), g() } function q() { I.show = !1, I.date = '', m.value.hide() } return e.onLoad((() => { e.index.showShareMenu() })), (n, r) => { return e.e({ a: e.p({ title: e.unref(I).title }), b: !!e.unref(I).userInfo.icon_uri }, e.unref(I).userInfo.icon_uri ? { c: e.unref(l) + e.unref(I).userInfo.icon_uri } : {}, { d: !e.unref(I).userInfo.icon_uri }, e.unref(I).userInfo.icon_uri ? {} : { e: o._imports_0$4 }, { f: e.o(k), g: e.o((o => p(e.unref(I).userInfo.nickname, 'nickname'))), h: e.o((o => b(e.unref(I).userInfo.nickname, 'nickname'))), i: e.unref(I).userInfo.nickname, j: e.o(e.m(o => e.unref(I).userInfo.nickname = o.detail.value, { trim: !0 })), k: e.t(e.unref(I).userInfo.gender === 1 ? '男' : e.unref(I).userInfo.gender === 2 ? '女' : '请选择'), l: e.p({ name: 'arrow-right', color: '#e0e0e0', size: '12' }), m: e.o(((e) => { return c.value.open(), void (I.focus_info.gender = (o = I == null ? void 0 : I.userInfo) == null ? void 0 : o.gender); let o })), n: e.sr(c, 'ce3c4538-2', { k: 'usersexRef' }), o: e.o(w), p: !e.unref(I).userInfo.birthday }, (e.unref(I).userInfo.birthday, {}), { q: !!e.unref(I).userInfo.birthday }, e.unref(I).userInfo.birthday ? { r: e.t((i = e.unref(I).userInfo.birthday, i ? `${i.replace('-', '年').replace('-', '月')}日` : '')) } : {}, { s: e.p({ name: 'arrow-right', color: '#e0e0e0', size: '12' }), t: e.o(((e) => { let o; I.userInfo.birthday || (m.value.show(), I.focus_info.birthday = (o = I == null ? void 0 : I.userInfo) == null ? void 0 : o.birthday) })), v: e.o((o => p(e.unref(I).userInfo.mobile, 'mobile'))), w: e.unref(I).userInfo.mobile, x: e.o((o => e.unref(I).userInfo.mobile = o.detail.value)), y: e.p({ name: 'arrow-right', color: '#e0e0e0', size: '12' }), z: e.o((o => p(e.unref(I).userInfo.redbook_id, 'redbook_id'))), A: e.o((o => b(e.unref(I).userInfo.redbook_id, 'redbook_id'))), B: e.unref(I).userInfo.redbook_id, C: e.o(e.m(o => e.unref(I).userInfo.redbook_id = o.detail.value, { trim: !0 })), D: e.o((o => p(e.unref(I).userInfo.weibo_id, 'weibo_id'))), E: e.o((o => b(e.unref(I).userInfo.weibo_id, 'weibo_id'))), F: e.unref(I).userInfo.weibo_id, G: e.o(e.m(o => e.unref(I).userInfo.weibo_id = o.detail.value, { trim: !0 })), H: e.o((o => p(e.unref(I).userInfo.tiktok_id, 'tiktok_id'))), I: e.o((o => b(e.unref(I).userInfo.tiktok_id, 'tiktok_id'))), J: e.unref(I).userInfo.tiktok_id, K: e.o(e.m(o => e.unref(I).userInfo.tiktok_id = o.detail.value, { trim: !0 })), L: e.sr(m, 'ce3c4538-5', { k: 'qs_picker_date' }), M: { startYear: (new Date()).getFullYear() - 100, endYear: (new Date()).getFullYear() + 100, dateMode: 3, dateFormatArray: ['-', '-', ' '], defaultValue: e.unref(v) }, N: e.o((e => j(e))), O: e.p({ 'title': '请选择', 'mode': 'bottom', 'type': 'date', 'picker-id': 'date_1', 'show-reset': !0, 'auto-hide': !1, 'content-color': '#000', 'line-height': 0.05 }), P: e.unref(I).show }, e.unref(I).show ? { Q: e.o(q), R: e.o(x) } : {}); let i }
  },
}; const c = e._export_sfc(f, [['__scopeId', 'data-v-ce3c4538']]); wx.createPage(c)
